huh_encore:
  js_entries:
    - { name: contao-video-bundle, file: "vendor/heimrichhannot/contao-video-bundle/src/Resources/assets/js/contao-video-bundle.js" }
    - { name: contao-video-bundle-theme, requires_css: true, file: "vendor/heimrichhannot/contao-video-bundle/src/Resources/assets/js/contao-video-bundle-theme.js" }
  unset_global_keys:
    js:
      - alertifyjs
      - contao-video-bundle
    css:
      - alertifyjs
      - contao-video-bundle