services:
  _defaults:
    autowire: true
    bind:
      $bundleConfig: '%huh_video%'

  HeimrichHannot\VideoBundle\Generator\VideoGenerator:
    public: true

  HeimrichHannot\VideoBundle\Collection\VideoProviderCollection:
    public: true

  HeimrichHannot\VideoBundle\EventListener\Dca\:
    resource: ../../EventListener/Dca/*
    public: true

  HeimrichHannot\VideoBundle\EventSubscriber\PrivacyCenterSubscriber:
    autoconfigure: true
    calls:
      - [setPrivacyCenterExtension, ['@?HeimrichHannot\PrivacyCenterBundle\Twig\PrivacyCenterExtension']]

  HeimrichHannot\VideoBundle\Controller\:
    resource: ../../Controller/*

  HeimrichHannot\VideoBundle\EventListener\LoadDataContainerListener:
    public: true

  HeimrichHannot\VideoBundle\EventListener\SqlGetDataListener:
    public: true

  HeimrichHannot\VideoBundle\EventListener\ParseArticlesListener:
    public: true

  HeimrichHannot\VideoBundle\Asset\FrontendAsset:
    public: true
    calls:
      - [setEncoreFrontendAsset, ['@?HeimrichHannot\EncoreBundle\Asset\FrontendAsset']]

  HeimrichHannot\VideoBundle\ConfigElementType\VideoConfigElementType:
    tags: ['huh.list.config_element_type', 'huh.reader.config_element_type']

  HeimrichHannot\VideoBundle\EventListener\InitializeSystemListener:
    public: true