services:
  _defaults:
    autowire: true
    bind:
      $bundleConfig: '%huh_video%'

  HeimrichHannot\VideoBundle\:
    resource: '../../{Asset,Command,Controller,EventListener}/*'
    autoconfigure: true

  HeimrichHannot\VideoBundle\Asset\FrontendAsset:
    public: true
    autoconfigure: true
    autowire: true

  HeimrichHannot\VideoBundle\Generator\VideoGenerator:
    public: true

  HeimrichHannot\VideoBundle\Collection\VideoProviderCollection:
    public: true

  HeimrichHannot\VideoBundle\EventListener\Dca\:
    resource: ../../EventListener/Dca/*
    public: true

  HeimrichHannot\VideoBundle\ConfigElementType\VideoConfigElementType:
    tags: ['huh.list.config_element_type', 'huh.reader.config_element_type']